name: Website Uptime Monitor

on:
  schedule:
    # Runs every 15 minutes.
    # Note: GitHub Actions can sometimes be delayed.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the monitoring script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python monitor.py
